language: python

python:
  - "2.7"

env:
  - TOXENV=py26-1.4.X,py27-1.4.X
  - TOXENV=py26-1.5.X,py27-1.5.X,py32-1.5.X
  - TOXENV=py26-1.5.X-swapped,py32-1.5.X-swapped

install:
  - pip install tox --use-mirrors

script:
    - tox

branches:
  only:
    - master