sudo: false

language: python

python:
  - "3.4"

env:
  - TOXENV=py27-django18-normal,py33-django18-normal
  - TOXENV=py27-django18-custom,py33-django18-custom
  - TOXENV=py27-django19-normal,py34-django19-normal
  - TOXENV=py27-django19-custom,py34-django19-custom
  - TOXENV=py27-django110-normal,py34-django110-normal,py35-django110-normal
  - TOXENV=py27-django110-custom,py34-django110-custom,py35-django110-custom

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox pip wheel codecov -U

script:
  - tox

after_success:
  - codecov -e TOX_ENV

branches:
  only:
    - master

deploy:
  provider: pypi
  user: mlavin
  password:
    secure: "TcTMW0Kxty9Wz3uedxYdTisKsUulx+/9Cls5qnm1/sE8McHmR719Qs5An7VA+XWuVq2fdAsyQw/JQI6gYbtLvkb8wyLJA7WggWG1/pAscIyFNRpKM0qvFWxXrSA7eSu1jG9z/kM68wfdTBmHTLGiyGqWuvtGzYy9KdNXEVKNUj0="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: mlavin/django-all-access
